permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://19ceng.github.io
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: seyyah
archive: Son Girdiler
assets: /assets
author: OMÜ FACE Blog
disqus: 19ceng
email: seyyah@bil.omu.edu.tr
facebook: ~
feed: ~
flickr: ~
google: ~
googleanalyticsid: ~
googleplus: ~
gpg: ~
logo: /assets/my/vision-128x128.png
organization: 19
picasa: ~
related: Diğer Girdiler
repository: 19ceng.github.io
ribbon: 19ceng
title: FACE Blog
twitter: ~

navigator:
        0: Genel
        1: Görüntü İşleme, Bilgisayarla Görü, Örüntü Tanıma, Makine Öğrenme, İstatistik, Deep Learning, Yapay Zeka, Donanım, Realtime
        2: Yayınlar ve kaynakça
        7: Projeler
        9: Eğitim-Öğretim

